import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { InMemoryTransport } from "@modelcontextprotocol/sdk/inMemory.js";
import type { Tool } from "@modelcontextprotocol/sdk/types.js";
import { fileURLToPath } from "node:url";
import { FreshdeskClient } from "../src/client.js";
import { createServer, SERVER_NAME, SERVER_VERSION } from "../src/server.js";

export const TOOL_DOCS_PATH = fileURLToPath(new URL("../docs/TOOLS.md", import.meta.url));

const EXAMPLES: Record<string, Record<string, unknown>> = {
  list_tickets: { requester_email: "priya.nair@example.com", updated_since: "2026-09-01", per_page: 10 },
  get_ticket: { ticket_id: 101 },
  list_ticket_conversations: { ticket_id: 101 },
  search_tickets: { status: ["Open", "Pending"], priority: ["Urgent"], created_after: "2026-09-01" },
  get_contact: { contact_id: 5001 },
  search_contacts: { email: "priya.nair@example.com" },
};

/** Starts the real server in memory (no network) and returns its tool definitions. */
export async function listToolDefinitions(): Promise<Tool[]> {
  const fd = new FreshdeskClient({
    baseUrl: "https://example.freshdesk.com",
    apiKey: "unused",
    timeoutMs: 1,
    maxRetries: 0,
    maxRetryWaitS: 0,
    maxConcurrency: 1,
  });
  const server = createServer(fd);
  const [a, b] = InMemoryTransport.createLinkedPair();
  const client = new Client({ name: "tool-docs", version: "0.0.0" });
  await Promise.all([server.connect(a), client.connect(b)]);
  const { tools } = await client.listTools();
  await client.close();
  return tools;
}

const json = (value: unknown) => "```json\n" + JSON.stringify(value, null, 2) + "\n```";

export function renderToolDocs(tools: Tool[]): string {
  const sorted = [...tools].sort((x, y) => x.name.localeCompare(y.name));
  const lines: string[] = [
    "# MCP tool specification",
    "",
    "<!-- Generated by `npm run docs:tools` from the registered tool schemas. Do not edit by hand. -->",
    "",
    `Server: \`${SERVER_NAME}\` v${SERVER_VERSION} · transports: stdio, Streamable HTTP (\`POST /mcp\`) · all tools are read-only.`,
    "",
    "Every successful result carries the payload twice: as `structuredContent` (validated against the output",
    "schema below) and as pretty-printed JSON text. Failures return `isError: true` with",
    '`{"error": {"type": "...", "message": "...", "retry_after_seconds"?: n}}`, where `type` is one of',
    "`ValidationError`, `AuthError`, `PermissionError`, `NotFoundError`, `RateLimitedError`, `UpstreamError`, `InternalError`.",
    "",
    "| Tool | Title |",
    "|---|---|",
    ...sorted.map((t) => `| [\`${t.name}\`](#${t.name}) | ${t.title ?? ""} |`),
    "",
  ];
  for (const tool of sorted) {
    const example = EXAMPLES[tool.name];
    lines.push(
      `## \`${tool.name}\``,
      "",
      tool.description ?? "",
      "",
      `**Annotations:** ${Object.entries(tool.annotations ?? {})
        .map(([k, v]) => `\`${k}: ${String(v)}\``)
        .join(", ")}`,
      "",
      "**Example call**",
      "",
      example ? json({ name: tool.name, arguments: example }) : "_No example_",
      "",
      "<details><summary>Input schema</summary>",
      "",
      json(tool.inputSchema),
      "",
      "</details>",
      "",
      "<details><summary>Output schema</summary>",
      "",
      json(tool.outputSchema ?? {}),
      "",
      "</details>",
      "",
    );
  }
  return lines.join("\n");
}
